### ISSUE TITLE
Unable to Validate Workspace due to `SyntaxError: Unexpected end of JSON input`

### ISSUE THREAD

**Issue by jakauppila** [chef/vscode-chef#141]
# Describe the problem
VSCode is unable to run rubocop on my cookbooks due to inability to parse output.

## Software Version
Windows 10
VSCode 1.57.1
Chef Infra Extension for Visual Studio Code 2.1.0

Cinc Workstation version: 21.7.524
Cinc Client version: 17.2.29
Cinc Auditor version: 4.38.3
Cinc CLI version: 5.3.0
Biome version: unknown
Test Kitchen version: 3.0.0
Cookstyle version: 7.15.1

## Stacktrace

I recently noticed that VSCode auto-rubocop execution started failing after a Workstation update (not sure which version I was on previously)

If I pop open the developer tools in VSCode, I see the following when the validation runs:

```
SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at validatePaths (c:\Users\USERNAME\.vscode\extensions\chef-software.chef-2.1.0\out\extension.js:116:34)
	at validateEntireWorkspace (c:\Users\USERNAME\.vscode\extensions\chef-software.chef-2.1.0\out\extension.js:102:5)
	at commandHandler (c:\Users\USERNAME\.vscode\extensions\chef-software.chef-2.1.0\out\extension.js:44:9)
	at _executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:108091)
	at _.$executeContributedCommand (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:84:108529)
	at d._doInvokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:88:12815)
	at d._invokeHandler (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:88:12507)
	at d._receiveRequest (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:88:11160)
	at d._receiveOneMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:88:9960)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:88:8064
	at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1835)
	at E.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15634)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:103:29816
	at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1835)
	at E.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:15634)
	at t._receiveMessage (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:20892)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:17778
	at l.fire (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:57:1835)
	at c.acceptChunk (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12995)
	at c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:65:12343
	at Socket.b (c:\Program Files\Microsoft VS Code\resources\app\out\vs\workbench\services\extensions\node\extensionHostProcess.js:103:13287)
	at Socket.emit (events.js:315:20)
	at addChunk (internal/streams/readable.js:309:12)
	at readableAddChunk (internal/streams/readable.js:284:9)
	at Socket.Readable.push (internal/streams/readable.js:223:10)
	at Pipe.onStreamRead (internal/stream_base_commons.js:188:23
```

If I run that [command](
https://github.com/chef/vscode-chef/blob/master/extension.ts#L117) directly `C:\opscode\chef-workstation\bin\cookstyle.bat --parallel -f j C:\git_workspaces\COOKBOOK\resources\tomcat.rb`, I get the following:

```
Process.fork is not supported by this Ruby
{"metadata":{"rubocop_version":"1.18.3","ruby_engine":"ruby","ruby_version":"3.0.1"..
```

I'm _guessing_ that that first line is getting caught in stdout making it unparsable?

Attempting to modify the extension locally and log out the stdout is coming back as empty

`console.log("Rubocop executed and exited with status: " + rubocop.status + rubocop.stdout);`

![image](https://user-images.githubusercontent.com/4100127/127519468-c4bb778d-bdf9-4c0a-a6a1-8e68edc63bc6.png)

**Comment by jakauppila** [comment]
User error. I had to update my `GEM_HOME`, `GEM_PATH`, and `GEM_ROOT` to the ruby 3.0.0 folder instead of 2.7.0.
